import type { MapDefinition } from '../types';

export const floor1: MapDefinition = {
  id: 'floor1',
  name: 'Tower Floor 1',
  layout: [
    '########################',
    '#....#.....#...........#',
    '#....#.....#.......#...#',
    '#....#.....#.......#...#',
    '#..........#...........#',
    '#....#.....#..######...#',
    '#....###.###..#...##...#',
    '#....#..#..#..#...##...#',
    '#....#..#.....#...##...#',
    '#....#.....#..######...#',
    '#.......#..#...........#',
    '###.#####.##.......#...#',
    '#....#.....###.###.#...#',
    '#..........#...........#',
    '#..........#...........#',
    '########################',
  ],
  entities: [
    {
      kind: 'portal',
      id: 'floor1-to-village',
      tile: { x: 2, y: 14 },
      assetId: 'stairs-up',
      target: { mapId: 'village', tile: { x: 11, y: 2 } },
    },
    {
      kind: 'portal',
      id: 'floor1-front-to-floor2',
      tile: { x: 9, y: 2 },
      assetId: 'stairs-down',
      target: { mapId: 'floor2', tile: { x: 8, y: 10 } },
      factId: 'floor1-depth-stairs-used',
      lock: {
        requiresItemId: 'tower-depth-sigil',
        lockedFactId: 'floor1-depth-seal-seen',
        lockedText: 'A crest-shaped socket seals the lower stair.',
      },
    },
    {
      kind: 'portal',
      id: 'floor1-rear-to-floor2',
      tile: { x: 21, y: 3 },
      assetId: 'stairs-down',
      target: { mapId: 'floor2', tile: { x: 16, y: 1 } },
      factId: 'floor1-rear-stairs-used',
    },
    {
      kind: 'clue',
      id: 'floor1-route-mark',
      tile: { x: 9, y: 4 },
      assetId: 'clue-runes',
      text: 'Route scratches point toward a connection that returns from below.',
      factId: 'floor1-route-mark-seen',
    },
    {
      kind: 'clue',
      id: 'floor1-treasury-overlook',
      tile: { x: 10, y: 3 },
      assetId: 'clue-runes',
      text: 'The arch facing the visible treasury is bricked from this side.',
      factId: 'floor1-treasury-sealed',
    },
    {
      kind: 'reward',
      id: 'floor1-ledger-fragment',
      tile: { x: 3, y: 4 },
      assetId: 'chest-relic-closed',
      grant: 'item',
      itemId: 'ledger-fragment-1',
      label: 'Ledger Fragment',
    },
    {
      kind: 'reward',
      id: 'floor1-west-cache',
      tile: { x: 7, y: 13 },
      assetId: 'chest-relic-closed',
      grant: 'stat',
      stat: 'defense',
      amount: 1,
    },
    {
      kind: 'reward',
      id: 'floor1-depth-sigil',
      tile: { x: 9, y: 10 },
      assetId: 'chest-relic-closed',
      grant: 'item',
      itemId: 'tower-depth-sigil',
      label: 'Tower Sigil',
    },
    {
      kind: 'enemy',
      id: 'floor1-west-sentry',
      tile: { x: 3, y: 11 },
      assetId: 'enemy-ruin-guard',
      stats: { hp: 18, attack: 6, defense: 3 },
    },
    {
      kind: 'enemy',
      id: 'floor1-east-sentry',
      tile: { x: 9, y: 11 },
      assetId: 'enemy-ruin-guard',
      stats: { hp: 22, attack: 7, defense: 4 },
    },
    {
      kind: 'latch',
      id: 'floor1-rear-latch',
      tile: { x: 11, y: 8 },
      rearSide: 'east',
    },
    {
      kind: 'reward',
      id: 'floor1-power-core',
      tile: { x: 13, y: 8 },
      assetId: 'chest-relic-closed',
      grant: 'stat',
      stat: 'attack',
      amount: 2,
    },
    {
      kind: 'enemy',
      id: 'floor1-gatekeeper',
      tile: { x: 15, y: 10 },
      assetId: 'enemy-ruin-guard',
      stats: { hp: 20, attack: 7, defense: 4 },
    },
    {
      kind: 'portal',
      id: 'floor1-treasury-to-floor2',
      tile: { x: 17, y: 7 },
      assetId: 'stairs-down',
      target: { mapId: 'floor2', tile: { x: 4, y: 2 } },
    },
    {
      kind: 'reward',
      id: 'floor1-future-treasury',
      tile: { x: 16, y: 7 },
      assetId: 'chest-relic-closed',
      grant: 'stat',
      stat: 'defense',
      amount: 2,
    },
  ],
  sections: [
    {
      id: 'floor1-entry-court',
      name: 'Entry Court',
      bounds: { minX: 1, maxX: 10, minY: 12, maxY: 14 },
      factIds: ['floor1-treasury-seen'],
    },
    {
      id: 'floor1-lower-loop',
      name: 'Lower Loop',
      bounds: { minX: 1, maxX: 10, minY: 7, maxY: 11 },
    },
    {
      id: 'floor1-upper-gallery',
      name: 'Upper Gallery',
      bounds: { minX: 1, maxX: 10, minY: 1, maxY: 6 },
    },
    {
      id: 'floor1-rear-wing',
      name: 'Rear Wing',
      bounds: { minX: 11, maxX: 22, minY: 1, maxY: 14 },
    },
    {
      id: 'floor1-workshop-treasury',
      name: 'Workshop Treasury',
      bounds: { minX: 15, maxX: 17, minY: 6, maxY: 8 },
    },
  ],
};
